var sourcesIndex = JSON.parse('{\
"adler":["",[],["algo.rs","lib.rs"]],\
"adler32":["",[],["lib.rs"]],\
"aliasable":["",[],["boxed.rs","lib.rs","mut_ref.rs","string.rs","vec.rs"]],\
"az":["",[],["float.rs","int.rs","lib.rs"]],\
"base64":["",[["read",[],["decoder.rs","mod.rs"]],["write",[],["encoder.rs","encoder_string_writer.rs","mod.rs"]]],["chunked_encoder.rs","decode.rs","display.rs","encode.rs","lib.rs","tables.rs"]],\
"bitflags":["",[],["lib.rs"]],\
"bytemuck":["",[],["anybitpattern.rs","checked.rs","contiguous.rs","internal.rs","lib.rs","no_uninit.rs","offset_of.rs","pod.rs","pod_in_option.rs","transparent.rs","zeroable.rs","zeroable_in_option.rs"]],\
"byteorder":["",[],["io.rs","lib.rs"]],\
"cfg_if":["",[],["lib.rs"]],\
"color_quant":["",[],["lib.rs","math.rs"]],\
"crc32fast":["",[["specialized",[],["mod.rs","pclmulqdq.rs"]]],["baseline.rs","combine.rs","lib.rs","table.rs"]],\
"critical_section":["",[],["lib.rs","mutex.rs"]],\
"crossbeam_channel":["",[["flavors",[],["array.rs","at.rs","list.rs","mod.rs","never.rs","tick.rs","zero.rs"]]],["channel.rs","context.rs","counter.rs","err.rs","lib.rs","select.rs","select_macro.rs","utils.rs","waker.rs"]],\
"crossbeam_deque":["",[],["deque.rs","lib.rs"]],\
"crossbeam_epoch":["",[["sync",[],["list.rs","mod.rs","once_lock.rs","queue.rs"]]],["atomic.rs","collector.rs","default.rs","deferred.rs","epoch.rs","guard.rs","internal.rs","lib.rs"]],\
"crossbeam_utils":["",[["atomic",[],["atomic_cell.rs","consume.rs","mod.rs","seq_lock.rs"]],["sync",[],["mod.rs","once_lock.rs","parker.rs","sharded_lock.rs","wait_group.rs"]]],["backoff.rs","cache_padded.rs","lib.rs","thread.rs"]],\
"deflate":["",[],["bit_reverse.rs","bitstream.rs","chained_hash_table.rs","checksum.rs","compress.rs","compression_options.rs","deflate_state.rs","encoder_state.rs","huffman_lengths.rs","huffman_table.rs","input_buffer.rs","length_encode.rs","lib.rs","lz77.rs","lzvalue.rs","matching.rs","output_writer.rs","rle.rs","stored_block.rs","writer.rs","zlib.rs"]],\
"either":["",[],["lib.rs"]],\
"embedded_alloc":["",[],["lib.rs"]],\
"embedded_dma":["",[],["lib.rs"]],\
"embedded_fps":["",[],["fps.rs","lib.rs","std_clock.rs"]],\
"embedded_graphics":["",[["draw_target",[],["clipped.rs","color_converted.rs","cropped.rs","mod.rs","translated.rs"]],["geometry",[],["angle.rs","mod.rs","real.rs"]],["image",[],["image_drawable_ext.rs","image_raw.rs","mod.rs","sub_image.rs"]],["iterator",[],["contiguous.rs","mod.rs","pixel.rs","raw.rs"]],["mock_display",[],["color_mapping.rs","fancy_panic.rs","mod.rs"]],["mono_font",[["generated",[],["ascii.rs","iso_8859_1.rs","iso_8859_10.rs","iso_8859_13.rs","iso_8859_14.rs","iso_8859_15.rs","iso_8859_16.rs","iso_8859_2.rs","iso_8859_3.rs","iso_8859_4.rs","iso_8859_5.rs","iso_8859_7.rs","iso_8859_9.rs","jis_x0201.rs","mod.rs"]]],["draw_target.rs","mapping.rs","mod.rs","mono_text_style.rs"]],["primitives",[["arc",[],["mod.rs","points.rs","styled.rs"]],["circle",[],["mod.rs","points.rs","styled.rs"]],["common",[],["closed_thick_segment_iter.rs","distance_iterator.rs","line_join.rs","linear_equation.rs","mod.rs","plane_sector.rs","scanline.rs","styled_scanline.rs","thick_segment.rs","thick_segment_iter.rs"]],["ellipse",[],["mod.rs","points.rs","styled.rs"]],["line",[],["bresenham.rs","intersection_params.rs","mod.rs","points.rs","styled.rs","thick_points.rs"]],["polyline",[],["mod.rs","points.rs","scanline_intersections.rs","scanline_iterator.rs","styled.rs"]],["rectangle",[],["mod.rs","styled.rs"]],["rounded_rectangle",[],["corner_radii.rs","ellipse_quadrant.rs","mod.rs","points.rs","styled.rs"]],["sector",[],["mod.rs","points.rs","styled.rs"]],["triangle",[],["mod.rs","points.rs","scanline_intersections.rs","scanline_iterator.rs","styled.rs"]]],["mod.rs","primitive_style.rs","styled.rs"]],["text",[["renderer",[],["character_style.rs","mod.rs"]]],["mod.rs","text.rs","text_style.rs"]]],["examples.rs","framebuffer.rs","lib.rs","prelude.rs","transform.rs"]],\
"embedded_graphics_core":["",[["draw_target",[],["mod.rs"]],["geometry",[],["mod.rs","point.rs","size.rs"]],["image",[],["mod.rs"]],["pixelcolor",[["raw",[],["mod.rs","to_bytes.rs"]]],["binary_color.rs","conversion.rs","gray_color.rs","mod.rs","rgb_color.rs","web_colors.rs"]],["primitives",[["rectangle",[],["mod.rs","points.rs"]]],["mod.rs"]]],["drawable.rs","lib.rs","prelude.rs"]],\
"embedded_graphics_framebuf":["",[],["backends.rs","lib.rs"]],\
"embedded_graphics_simulator":["",[["window",[],["mod.rs","sdl_window.rs"]]],["display.rs","lib.rs","output_image.rs","output_settings.rs","theme.rs"]],\
"embedded_hal":["",[["blocking",[],["can.rs","delay.rs","i2c.rs","mod.rs","rng.rs","serial.rs","spi.rs"]],["can",[],["id.rs","mod.rs","nb.rs"]],["digital",[],["mod.rs","v1.rs","v1_compat.rs","v2.rs","v2_compat.rs"]]],["adc.rs","fmt.rs","lib.rs","prelude.rs","serial.rs","spi.rs","timer.rs","watchdog.rs"]],\
"embedded_time":["",[],["clock.rs","duration.rs","fixed_point.rs","fraction.rs","instant.rs","lib.rs","rate.rs","time_int.rs","timer.rs"]],\
"float_cmp":["",[],["eq.rs","lib.rs","macros.rs","ratio.rs","ulps.rs","ulps_eq.rs"]],\
"genio":["",[["util",[],["bytes.rs","chain.rs","empty.rs","mod.rs","repeat.rs","repeat_bytes.rs","restarting.rs","sink.rs","write_trunc.rs"]]],["bufio.rs","error.rs","ext.rs","lib.rs","std_impls.rs"]],\
"gif":["",[["reader",[],["decoder.rs","mod.rs"]]],["common.rs","encoder.rs","lib.rs","traits.rs"]],\
"hash32":["",[],["fnv.rs","lib.rs","murmur3.rs"]],\
"heapless":["",[["pool",[["singleton",[],["arc.rs"]]],["cas.rs","mod.rs","singleton.rs"]]],["binary_heap.rs","deque.rs","histbuf.rs","indexmap.rs","indexset.rs","lib.rs","linear_map.rs","mpmc.rs","sealed.rs","sorted_linked_list.rs","spsc.rs","string.rs","vec.rs"]],\
"image":["",[["codecs",[["bmp",[],["decoder.rs","encoder.rs","mod.rs"]],["hdr",[],["decoder.rs","encoder.rs","mod.rs"]],["ico",[],["decoder.rs","encoder.rs","mod.rs"]],["jpeg",[],["decoder.rs","encoder.rs","entropy.rs","mod.rs","transform.rs"]],["pnm",[],["autobreak.rs","decoder.rs","encoder.rs","header.rs","mod.rs"]],["tga",[],["decoder.rs","encoder.rs","header.rs","mod.rs"]],["webp",[],["decoder.rs","mod.rs","transform.rs","vp8.rs"]]],["dds.rs","dxt.rs","farbfeld.rs","gif.rs","png.rs","tiff.rs"]],["imageops",[],["affine.rs","colorops.rs","mod.rs","sample.rs"]],["io",[],["free_functions.rs","mod.rs","reader.rs"]],["math",[],["mod.rs","nq.rs","rect.rs","utils.rs"]],["utils",[],["mod.rs"]]],["animation.rs","buffer.rs","color.rs","dynimage.rs","error.rs","flat.rs","image.rs","lib.rs","traits.rs"]],\
"inflector":["",[["cases",[["camelcase",[],["mod.rs"]],["case",[],["mod.rs"]],["classcase",[],["mod.rs"]],["kebabcase",[],["mod.rs"]],["pascalcase",[],["mod.rs"]],["screamingsnakecase",[],["mod.rs"]],["sentencecase",[],["mod.rs"]],["snakecase",[],["mod.rs"]],["tablecase",[],["mod.rs"]],["titlecase",[],["mod.rs"]],["traincase",[],["mod.rs"]]],["mod.rs"]],["numbers",[["deordinalize",[],["mod.rs"]],["ordinalize",[],["mod.rs"]]],["mod.rs"]],["suffix",[["foreignkey",[],["mod.rs"]]],["mod.rs"]]],["lib.rs"]],\
"jpeg_decoder":["",[["worker",[],["immediate.rs","mod.rs","multithreaded.rs"]]],["decoder.rs","error.rs","huffman.rs","idct.rs","lib.rs","marker.rs","parser.rs","upsampler.rs"]],\
"lazy_static":["",[],["inline_lazy.rs","lib.rs"]],\
"libc":["",[["unix",[["bsd",[["apple",[["b64",[["x86_64",[],["align.rs","mod.rs"]]],["mod.rs"]]],["long_array.rs","mod.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["fixed_width_ints.rs","lib.rs","macros.rs"]],\
"linked_list_allocator":["",[],["hole.rs","lib.rs"]],\
"lock_api":["",[],["lib.rs","mutex.rs","remutex.rs","rwlock.rs"]],\
"memoffset":["",[],["lib.rs","offset_of.rs","raw_field.rs","span_of.rs"]],\
"micromath":["",[["float",[],["abs.rs","acos.rs","asin.rs","atan.rs","atan2.rs","ceil.rs","copysign.rs","cos.rs","div_euclid.rs","exp.rs","floor.rs","fract.rs","hypot.rs","inv.rs","invsqrt.rs","ln.rs","log.rs","log10.rs","log2.rs","powf.rs","powi.rs","rem_euclid.rs","round.rs","sin.rs","sqrt.rs","tan.rs","trunc.rs"]]],["f32ext.rs","float.rs","lib.rs"]],\
"miniz_oxide":["",[["deflate",[],["buffer.rs","core.rs","mod.rs","stream.rs"]],["inflate",[],["core.rs","mod.rs","output_buffer.rs","stream.rs"]]],["lib.rs","shared.rs"]],\
"num":["",[],["lib.rs"]],\
"num_complex":["",[],["cast.rs","lib.rs","pow.rs"]],\
"num_cpus":["",[],["lib.rs"]],\
"num_integer":["",[],["average.rs","lib.rs","roots.rs"]],\
"num_iter":["",[],["lib.rs"]],\
"num_rational":["",[],["lib.rs","pow.rs"]],\
"num_traits":["",[["ops",[],["checked.rs","euclid.rs","inv.rs","mod.rs","mul_add.rs","overflowing.rs","saturating.rs","wrapping.rs"]]],["bounds.rs","cast.rs","float.rs","identities.rs","int.rs","lib.rs","macros.rs","pow.rs","real.rs","sign.rs"]],\
"ouroboros":["",[],["lib.rs"]],\
"ouroboros_macro":["",[["generate",[],["constructor.rs","derives.rs","into_heads.rs","mod.rs","struc.rs","summon_checker.rs","try_constructor.rs","type_asserts.rs","with_all.rs","with_each.rs"]]],["covariance_detection.rs","info_structures.rs","lib.rs","parse.rs","utils.rs"]],\
"png":["",[["decoder",[],["mod.rs","stream.rs","zlib.rs"]]],["chunk.rs","common.rs","encoder.rs","filter.rs","lib.rs","traits.rs","utils.rs"]],\
"proc_macro2":["",[],["detection.rs","extra.rs","fallback.rs","lib.rs","marker.rs","parse.rs","rcvec.rs","wrapper.rs"]],\
"proc_macro_error":["",[["imp",[],["fallback.rs"]]],["diagnostic.rs","dummy.rs","lib.rs","macros.rs","sealed.rs"]],\
"proc_macro_error_attr":["",[],["lib.rs","parse.rs","settings.rs"]],\
"quote":["",[],["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]],\
"rayon":["",[["collections",[],["binary_heap.rs","btree_map.rs","btree_set.rs","hash_map.rs","hash_set.rs","linked_list.rs","mod.rs","vec_deque.rs"]],["compile_fail",[],["cannot_collect_filtermap_data.rs","cannot_zip_filtered_data.rs","cell_par_iter.rs","mod.rs","must_use.rs","no_send_par_iter.rs","rc_par_iter.rs"]],["iter",[["collect",[],["consumer.rs","mod.rs"]],["find_first_last",[],["mod.rs"]],["plumbing",[],["mod.rs"]]],["chain.rs","chunks.rs","cloned.rs","copied.rs","empty.rs","enumerate.rs","extend.rs","filter.rs","filter_map.rs","find.rs","flat_map.rs","flat_map_iter.rs","flatten.rs","flatten_iter.rs","fold.rs","fold_chunks.rs","fold_chunks_with.rs","for_each.rs","from_par_iter.rs","inspect.rs","interleave.rs","interleave_shortest.rs","intersperse.rs","len.rs","map.rs","map_with.rs","mod.rs","multizip.rs","noop.rs","once.rs","panic_fuse.rs","par_bridge.rs","positions.rs","product.rs","reduce.rs","repeat.rs","rev.rs","skip.rs","skip_any.rs","skip_any_while.rs","splitter.rs","step_by.rs","sum.rs","take.rs","take_any.rs","take_any_while.rs","try_fold.rs","try_reduce.rs","try_reduce_with.rs","unzip.rs","update.rs","while_some.rs","zip.rs","zip_eq.rs"]],["slice",[],["chunks.rs","mergesort.rs","mod.rs","quicksort.rs","rchunks.rs"]]],["array.rs","delegate.rs","lib.rs","math.rs","option.rs","par_either.rs","prelude.rs","private.rs","range.rs","range_inclusive.rs","result.rs","split_producer.rs","str.rs","string.rs","vec.rs"]],\
"rayon_core":["",[["broadcast",[],["mod.rs"]],["compile_fail",[],["mod.rs","quicksort_race1.rs","quicksort_race2.rs","quicksort_race3.rs","rc_return.rs","rc_upvar.rs","scope_join_bad.rs"]],["join",[],["mod.rs"]],["scope",[],["mod.rs"]],["sleep",[],["counters.rs","mod.rs"]],["spawn",[],["mod.rs"]],["thread_pool",[],["mod.rs"]]],["job.rs","latch.rs","lib.rs","log.rs","private.rs","registry.rs","unwind.rs"]],\
"rtic_monotonic":["",[],["lib.rs"]],\
"scoped_threadpool":["",[],["lib.rs"]],\
"scopeguard":["",[],["lib.rs"]],\
"sdl2":["",[["keyboard",[],["keycode.rs","mod.rs","scancode.rs"]],["mouse",[],["mod.rs","relative.rs"]]],["audio.rs","clipboard.rs","common.rs","controller.rs","cpuinfo.rs","event.rs","filesystem.rs","haptic.rs","hint.rs","joystick.rs","lib.rs","log.rs","macros.rs","messagebox.rs","pixels.rs","rect.rs","render.rs","rwops.rs","sdl.rs","surface.rs","timer.rs","touch.rs","url.rs","version.rs","video.rs"]],\
"sdl2_sys":["",[],["lib.rs"]],\
"spin":["",[["mutex",[],["spin.rs"]]],["barrier.rs","lazy.rs","lib.rs","mutex.rs","once.rs","relax.rs","rwlock.rs"]],\
"stable_deref_trait":["",[],["lib.rs"]],\
"tiff":["",[["decoder",[],["ifd.rs","mod.rs","stream.rs"]],["encoder",[],["colortype.rs","mod.rs","writer.rs"]]],["bytecast.rs","error.rs","lib.rs","tags.rs"]],\
"trowel":["",[["pc",[],["fs.rs"]]],["buffered.rs","flipped.rs","fps.rs","fs.rs","lib.rs","pc.rs"]],\
"trowel_macro":["",[],["lib.rs"]],\
"try_default":["",[],["lib.rs"]],\
"unicode_ident":["",[],["lib.rs","tables.rs"]],\
"usb_device":["",[],["bus.rs","class.rs","control.rs","control_pipe.rs","descriptor.rs","device.rs","device_builder.rs","endpoint.rs","lib.rs","test_class.rs"]],\
"usbd_serial":["",[],["buffer.rs","cdc_acm.rs","lib.rs","serial_port.rs"]],\
"void":["",[],["lib.rs"]],\
"weezl":["",[],["decode.rs","encode.rs","error.rs","lib.rs"]]\
}');
createSourceSidebar();
